// Copyright (c) ArcForges. Licensed under the MIT License.

using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ArcChat.IconCodegen;

[Generator(LanguageNames.CSharp)]
public sealed class IconSourceGenerator : IIncrementalGenerator
{
    private const string IconRootMarker = "/Resources/Icons/";
    private const string ResourceUriPrefix = "avares://ArcChat.Desktop/Resources/Icons/";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<IconAsset> icons = context.AdditionalTextsProvider
            .Where(static file => IsIconFile(file.Path))
            .Select(static (file, _) => CreateIconAsset(file.Path));

        context.RegisterSourceOutput(icons.Collect(), static (context, iconAssets) => Execute(context, iconAssets));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<IconAsset> iconAssets)
    {
        if (iconAssets.IsDefaultOrEmpty)
        {
            return;
        }

        List<IconAsset> sortedAssets = iconAssets
            .Distinct()
            .OrderBy(static asset => asset.PropertyStem, StringComparer.Ordinal)
            .ThenBy(static asset => string.Equals(asset.Extension, ".svg", StringComparison.OrdinalIgnoreCase) ? 0 : 1)
            .ThenBy(static asset => asset.RelativePath, StringComparer.Ordinal)
            .ToList();
        HashSet<string> usedNames = new HashSet<string>(StringComparer.Ordinal);
        StringBuilder source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated />");
        _ = source.AppendLine();
        _ = source.AppendLine("namespace ArcChat.Desktop.Resources;");
        _ = source.AppendLine();
        _ = source.AppendLine("public static partial class Icons");
        _ = source.AppendLine("{");

        foreach (IconAsset asset in sortedAssets)
        {
            string propertyName = CreateUniquePropertyName(asset, usedNames);
            _ = source.Append("    public static string ");
            _ = source.Append(propertyName);
            _ = source.Append(" { get; } = ");
            _ = source.Append(ToLiteral(ResourceUriPrefix + asset.RelativePath));
            _ = source.AppendLine(";");
        }

        _ = source.AppendLine("}");
        context.AddSource("Icons.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static bool IsIconFile(string path)
    {
        string normalizedPath = NormalizePath(path);
        if (normalizedPath.IndexOf(IconRootMarker, StringComparison.OrdinalIgnoreCase) < 0)
        {
            return false;
        }

        string extension = Path.GetExtension(normalizedPath);
        return string.Equals(extension, ".svg", StringComparison.OrdinalIgnoreCase)
            || string.Equals(extension, ".png", StringComparison.OrdinalIgnoreCase);
    }

    private static IconAsset CreateIconAsset(string path)
    {
        string normalizedPath = NormalizePath(path);
        int markerIndex = normalizedPath.IndexOf(IconRootMarker, StringComparison.OrdinalIgnoreCase);
        string relativePath = normalizedPath.Substring(markerIndex + IconRootMarker.Length);
        string extension = Path.GetExtension(relativePath);
        string relativeWithoutExtension = relativePath.Substring(0, relativePath.Length - extension.Length);
        return new IconAsset(relativePath, extension, ToPropertyName(relativeWithoutExtension));
    }

    private static string CreateUniquePropertyName(IconAsset asset, HashSet<string> usedNames)
    {
        string propertyName = asset.PropertyStem;
        if (usedNames.Add(propertyName))
        {
            return propertyName;
        }

        string extensionSuffix = ToPropertyName(asset.Extension.TrimStart('.'));
        propertyName = asset.PropertyStem + extensionSuffix;
        int suffix = 2;
        while (!usedNames.Add(propertyName))
        {
            propertyName = asset.PropertyStem + extensionSuffix + suffix.ToString(CultureInfo.InvariantCulture);
            suffix++;
        }

        return propertyName;
    }

    private static string ToPropertyName(string path)
    {
        string[] segments = path.Split(new[] { '/', '\\', '-', '_', '.', ' ' }, StringSplitOptions.RemoveEmptyEntries);
        StringBuilder builder = new StringBuilder();
        foreach (string segment in segments)
        {
            AppendPascalSegment(builder, segment);
        }

        if (builder.Length == 0)
        {
            return "Icon";
        }

        if (char.IsDigit(builder[0]))
        {
            _ = builder.Insert(0, "Icon");
        }

        return builder.ToString();
    }

    private static void AppendPascalSegment(StringBuilder builder, string segment)
    {
        bool capitalizeNext = true;
        foreach (char value in segment)
        {
            if (!char.IsLetterOrDigit(value))
            {
                capitalizeNext = true;
                continue;
            }

            if (capitalizeNext)
            {
                _ = builder.Append(char.ToUpperInvariant(value));
                capitalizeNext = false;
            }
            else
            {
                _ = builder.Append(value);
            }
        }
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('\\', '/');
    }

    private static string ToLiteral(string value)
    {
        return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }

    private readonly struct IconAsset : IEquatable<IconAsset>
    {
        public IconAsset(string relativePath, string extension, string propertyStem)
        {
            this.RelativePath = relativePath;
            this.Extension = extension;
            this.PropertyStem = propertyStem;
        }

        public string RelativePath { get; }

        public string Extension { get; }

        public string PropertyStem { get; }

        public bool Equals(IconAsset other)
        {
            return string.Equals(this.RelativePath, other.RelativePath, StringComparison.OrdinalIgnoreCase);
        }

        public override bool Equals(object? obj)
        {
            return obj is IconAsset other && this.Equals(other);
        }

        public override int GetHashCode()
        {
            return StringComparer.OrdinalIgnoreCase.GetHashCode(this.RelativePath);
        }
    }
}
