CREATE TABLE IF NOT EXISTS Conversation (
  Id TEXT NOT NULL PRIMARY KEY,
  Topic TEXT NOT NULL,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Message (
  ConversationId TEXT NOT NULL,
  Id TEXT NOT NULL,
  Ordinal INTEGER NOT NULL,
  Json TEXT NOT NULL,
  CreatedAt INTEGER NOT NULL,
  PRIMARY KEY (ConversationId, Id),
  FOREIGN KEY (ConversationId) REFERENCES Conversation(Id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_Message_Conversation_Ordinal ON Message (ConversationId, Ordinal);

CREATE TABLE IF NOT EXISTS Mask (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Plugin (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS McpServer (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS HtmlArtifactPreview (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Setting (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SyncMeta (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SyncBackup (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ToolCall (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PromptSeed (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS KeychainRef (
  Id TEXT NOT NULL PRIMARY KEY,
  Json TEXT NOT NULL,
  UpdatedAt INTEGER NOT NULL
);
